version: "3.9"

services:
  app:
    build: ./docker/app
    volumes:
      - ./src/:/app
  web:
    build: ./docker/web
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./src/:/app
  db:
    build: ./docker/db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: $TZ
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
